analyze_pr_task:
  description: >
    Fetch information about GitHub pull request #{pr_number} from repository {repo_name} using the get_pr_info tool.
    Then collect all relevant files from this PR using the collect_pr_files tool.
    Return ONLY the output from collect_pr_files tool, which should be a JSON object where keys are file paths and values are file contents.
    Do not provide any additional summary or analysis - just return the raw file collection result.
  expected_output: >
    A JSON object where each key is a file path (string) and each value is the file content (string).
    Example format: {"src/App.js": "// file content here", "package.json": "{\"name\": \"project\"}"}
    This should be the exact output from the collect_pr_files tool.

  agent: github_pr_agent
