refine_code_task:
  description: >
    Analyze and improve the single code file: {file_path}
    
    File content:
    ```{file_extension}
    {file_content}
    ```
    
    Apply an IMPROVEMENT-FOCUSED APPROACH to this file:
    - Fix all syntax errors, missing imports, type issues, and obvious bugs
    - Improve code quality, readability, and maintainability
    - Optimize performance where beneficial and safe
    - Apply modern patterns and best practices when appropriate
    - Refactor code for better structure and clarity
    - DO NOT add new features or capabilities beyond what's needed
    - DO NOT add new libraries unless absolutely necessary for fixes
    - Focus on: error fixes, code improvements, performance optimizations, better patterns
    - Avoid: adding unnecessary features, introducing new dependencies
    
    For the file {file_path}:
    1. Analyze the current code for issues and improvement opportunities
    2. Apply fixes and improvements while maintaining original functionality
    3. Return the refined code in the specified format
    
  expected_output: >
    Return the refined content in this EXACT format. CRITICAL: Use newline character after colon, NOT space:

    ### Changes:
    - A bullet-point summary of what was changed (ONLY essential fixes).

    ### Updated Code:
    ```{file_extension}
    <ONLY THE NEW/IMPROVED CODE HERE>
    ```

    ⚠️ CRITICAL REQUIREMENTS:
    4. Do NOT use <think> tags or any other XML-like tags
    5. Provide bullet-point summary of changes under the `### Changes:` heading (with newline after colon)
    6. Provide ONLY ONE code block under the `### Updated Code:` heading (with newline after colon)
    9. The response must start with `### Changes:` and end with the code block
    12. Do NOT convert file types or change file structure
    13. **IF NO ESSENTIAL FIXES ARE NEEDED:**
        - In the ### Changes: section, write: 'No essential changes needed.'
        - In the ### Updated Code: section, return the original code unchanged.
    15. **EXACT FORMATTING**: CRITICAL - Use "### Changes:" followed by a NEWLINE character, NOT a space. Same for "### Updated Code:"
    16. **FORMAT ENFORCEMENT**: The headings must be exactly "### Changes:" and "### Updated Code:" with a newline character immediately after the colon
  agent: code_refiner_agent